/**
 * Type definitions for Supabase Database
 * This file would typically be auto-generated by Supabase CLI
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'admin' | 'editor' | 'viewer'
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'admin' | 'editor' | 'viewer'
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'admin' | 'editor' | 'viewer'
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      collections: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          type: 'post' | 'page' | 'custom'
          fields: Json
          settings: Json
          icon: string | null
          color: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          type?: 'post' | 'page' | 'custom'
          fields?: Json
          settings?: Json
          icon?: string | null
          color?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          type?: 'post' | 'page' | 'custom'
          fields?: Json
          settings?: Json
          icon?: string | null
          color?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      entries: {
        Row: {
          id: string
          collection_id: string
          title: string
          slug: string
          content: Json
          excerpt: string | null
          featured_image: string | null
          status: 'draft' | 'published' | 'archived'
          published_at: string | null
          author_id: string
          meta: Json
          tags: string[]
          version: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          collection_id: string
          title: string
          slug: string
          content?: Json
          excerpt?: string | null
          featured_image?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          author_id: string
          meta?: Json
          tags?: string[]
          version?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          collection_id?: string
          title?: string
          slug?: string
          content?: Json
          excerpt?: string | null
          featured_image?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          author_id?: string
          meta?: Json
          tags?: string[]
          version?: number
          created_at?: string
          updated_at?: string
        }
      }
      media: {
        Row: {
          id: string
          filename: string
          original_name: string
          mime_type: string
          size_bytes: number
          storage_path: string
          bucket_name: string
          dimensions: Json | null
          alt_text: string | null
          caption: string | null
          metadata: Json
          uploaded_by: string
          folder_path: string
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          filename: string
          original_name: string
          mime_type: string
          size_bytes: number
          storage_path: string
          bucket_name?: string
          dimensions?: Json | null
          alt_text?: string | null
          caption?: string | null
          metadata?: Json
          uploaded_by: string
          folder_path?: string
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          filename?: string
          original_name?: string
          mime_type?: string
          size_bytes?: number
          storage_path?: string
          bucket_name?: string
          dimensions?: Json | null
          alt_text?: string | null
          caption?: string | null
          metadata?: Json
          uploaded_by?: string
          folder_path?: string
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      entry_revisions: {
        Row: {
          id: string
          entry_id: string
          version: number
          title: string
          content: Json
          excerpt: string | null
          meta: Json | null
          revised_by: string
          revision_notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          entry_id: string
          version: number
          title: string
          content: Json
          excerpt?: string | null
          meta?: Json | null
          revised_by: string
          revision_notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          entry_id?: string
          version?: number
          title?: string
          content?: Json
          excerpt?: string | null
          meta?: Json | null
          revised_by?: string
          revision_notes?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_role: {
        Args: { user_id: string }
        Returns: 'admin' | 'editor' | 'viewer'
      }
      can_edit_content: {
        Args: { user_id: string }
        Returns: boolean
      }
    }
    Enums: {
      user_role: 'admin' | 'editor' | 'viewer'
      content_status: 'draft' | 'published' | 'archived'
      collection_type: 'post' | 'page' | 'custom'
    }
  }
}