-- ============================================================
-- kibanCMS — Migration 007: Channel Manager
-- ============================================================
-- Tabelas para o add-on Channel Manager. Liga o KIBAN a Channel
-- Managers existentes (Bokun, FareHarbor, Cloudbeds, …) que tratam
-- da distribuição multi-canal (Viator/TripAdvisor, GetYourGuide,
-- Booking, etc.). O KIBAN actua como o backoffice; o CM é a fonte
-- de verdade para inventário e bookings vindos de OTAs.
--
-- Bookings recebidos via webhook continuam a aterrar em `entries`
-- (a tabela genérica que já guarda bookings do KIBAN), com
-- `metadata.source='bokun'` e `metadata.external_id=<bokun id>`,
-- para que apareçam na UI existente sem código novo.
--
-- INSTRUÇÕES (Supabase Dashboard):
--   1. SQL Editor → New query
--   2. Cola este ficheiro → Run
--   3. Voltar a correr é seguro (idempotente)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- One row per (tenant, provider). Stores credentials and sync state.
CREATE TABLE IF NOT EXISTS channel_connections (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    provider TEXT NOT NULL,             -- 'bokun', 'fareharbor', ...
    enabled BOOLEAN NOT NULL DEFAULT true,
    -- credentials are intentionally JSONB so each provider can shape its
    -- own auth (api_key+secret, oauth tokens, …). The admin-side schema
    -- defines per-provider fields. Never logged in plaintext.
    credentials JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Shared secret used to verify HMAC signatures on inbound webhooks.
    -- Generated by the CMS, copy-pasted into the provider dashboard.
    webhook_secret TEXT,
    last_sync_at TIMESTAMPTZ,
    last_sync_status TEXT,              -- 'ok' | 'error' | 'partial'
    last_sync_error TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(provider)
);

CREATE INDEX IF NOT EXISTS channel_connections_enabled_idx
  ON channel_connections (enabled) WHERE enabled = true;

-- Append-only audit log of every webhook the CMS receives. Lets ops trace
-- a booking back to the raw provider payload, and the UNIQUE constraint
-- gives us idempotency for free — providers occasionally redeliver.
CREATE TABLE IF NOT EXISTS channel_bookings_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    provider TEXT NOT NULL,
    external_id TEXT NOT NULL,          -- e.g. Bokun booking ID
    event_type TEXT NOT NULL,           -- 'booking.created' | 'booking.cancelled' | ...
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'received',  -- 'received' | 'processed' | 'error' | 'duplicate'
    error TEXT,
    -- When we successfully convert a webhook into an `entries` booking row,
    -- we link it here so the audit log can jump to the live record.
    entry_id UUID REFERENCES entries(id) ON DELETE SET NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    UNIQUE(provider, external_id, event_type)
);

CREATE INDEX IF NOT EXISTS channel_bookings_log_received_idx
  ON channel_bookings_log (received_at DESC);
CREATE INDEX IF NOT EXISTS channel_bookings_log_status_idx
  ON channel_bookings_log (status);

ALTER TABLE channel_connections   ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_bookings_log  ENABLE ROW LEVEL SECURITY;

-- Drop+recreate so re-runs always end with the latest policy definition.
DROP POLICY IF EXISTS "Admins can manage channel connections" ON channel_connections;
DROP POLICY IF EXISTS "Admins can read channel bookings log"  ON channel_bookings_log;

-- Connections are admin-only — credentials live here.
CREATE POLICY "Admins can manage channel connections"
ON channel_connections FOR ALL TO authenticated
USING (
  EXISTS (SELECT 1 FROM profiles
          WHERE profiles.id = auth.uid()
            AND profiles.role::text IN ('super_admin', 'admin'))
)
WITH CHECK (
  EXISTS (SELECT 1 FROM profiles
          WHERE profiles.id = auth.uid()
            AND profiles.role::text IN ('super_admin', 'admin'))
);

-- Audit log is read-only for admins (writes happen via service_role
-- in the webhook handler, which bypasses RLS).
CREATE POLICY "Admins can read channel bookings log"
ON channel_bookings_log FOR SELECT TO authenticated
USING (
  EXISTS (SELECT 1 FROM profiles
          WHERE profiles.id = auth.uid()
            AND profiles.role::text IN ('super_admin', 'admin', 'editor'))
);

-- Register the add-on so it shows up as installed/enabled in the admin
-- list. Harmless if the registry table doesn't exist yet (run 006 first).
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_name = 'addon_registry') THEN
    INSERT INTO addon_registry (addon_id, status)
    VALUES ('channel-manager', '{"installed": true, "enabled": true}'::jsonb)
    ON CONFLICT (addon_id) DO NOTHING;
  END IF;
END $$;
